#pragma once

#include <vector>
#include <memory>
#include <stdexcept>
#include "lexer/Lexer.h"
#include "ast/Expr.h"

class Parser {
    public:
        // Ensures that the parser consunes the tokens generated by the lexer
        explicit Parser(const std::vector<Token>& tokens);

        // The MAIN entry point. It will eventually return a full tree.
        ASTNodePtr parse();

    private:
        const std::vector<Token>& m_tokens;
        int m_current = 0; // Tracks where we are in the token list

        //* ==== The recursive Descent Functions that will be helpful ====

        // This is the entry point for parsing expressionsand will call other functions
        ASTNodePtr expression();

        // Parses equality expressions. This function handles operators with equality
        // precedence and calls `comparison()`
        ASTNodePtr equality();
        
        // Parses comparison expressions. This function handles operators w/ comparison precedence and calls `term()`
        // in order to parse the operands.
        ASTNodePtr comparison();

        // Parses terms. This function handles addition and subtraction operators and calls
        // to parse the operands.
        ASTNodePtr term();

        // This function handles multiplication and division & calls `unary()`
        // to parse the operands.
        ASTNodePtr factor();

        // This function handles unary operators (e.g. negation, logical NOT) and calls `primary()`
        // to parse the operand.
        ASTNodePtr unary();

        // This is the lowest level of the grammar and directly handles tokens like numbers.
        // Strings, variables, or parenthesized expressions.
        ASTNodePtr primary();

        //* ==== Helper Functions to navigate the token stream ====

        // Checks if the current token matches any of the given types.
        // If a match is found, it advances the token stream and returns `true`
        // Otherwise, it returns `false`.
        bool match(std::initializer_list<TokenType> types);

        // Checks if the current token matches the given type without advancing the token stream
        bool check(TokenType type) const;

        // Returns true if the parser has reached the end of the token stream.
        bool isAtEnd() const;

        // Advances the token stream by one and returns theprevious token.
        Token advance();

        // Returns the current token without advancing the token stream.
        Token peek() const;

        // Returns the most recently consumed token.
        Token previous() const;

        //* ==== ERROR HANDLING =====
        Token consume(TokenType type, const std::string& message);
        std::runtime_error error(Token token, const std::string& message);
};